# Generated by Django 2.1.7 on 2019-06-05 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='reservation_state',
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.CharField(choices=[('NO', 'Not Ordered'), ('CH', 'Changed Order'), ('OR', 'Ordered'), ('PR', 'Preparing'), ('RE', 'Ready')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 20, 30, 15, 187171, tzinfo=utc)),
        ),
    ]
