# Generated by Django 2.1.7 on 2019-05-11 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20190325_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='takeaway',
            field=models.BooleanField(default=False, verbose_name='بیرون\u200cبر'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 8, 4, 35, 621800, tzinfo=utc)),
        ),
    ]
