# Generated by Django 2.2 on 2019-04-25 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20190325_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 13, 20, 30, 210520, tzinfo=utc)),
        ),
    ]
