# Generated by Django 2.2 on 2019-04-28 15:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0003_auto_20190425_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sub_lastName',
            field=models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_address',
            field=models.CharField(max_length=1000, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد اشتراک'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_mobile_phone',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message="your number isn't correct.\n                                        true formats :\n                                        1) +989999999999 2)09999999999", regex='^(\\+98|0)?9\\d{9}')], verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_phone',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='0(21|26|25|86|24|23|81|28|31|44|11|74|83|51|45|17|41|54|87|71|66|34|56|13|77|76|61|38|58|35|84)[0-9]+')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 15, 31, 52, 146399, tzinfo=utc)),
        ),
    ]
