# Generated by Django 2.2 on 2019-04-28 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_auto_20190428_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_lastName',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 15, 32, 23, 29531, tzinfo=utc)),
        ),
    ]
