# Generated by Django 2.2 on 2019-04-28 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0005_auto_20190428_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 15, 33, 13, 363572, tzinfo=utc)),
        ),
    ]
