# Generated by Django 2.2 on 2019-04-28 15:47

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0006_auto_20190428_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_phone',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='0(21|26|25|86|24|23|81|28|31|44|11|74|83|51|45|17|41|54|87|71|66|34|56|13|77|76|61|38|58|35|84)[0-9]+')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 15, 47, 35, 110751, tzinfo=utc)),
        ),
    ]
