# Generated by Django 2.2 on 2019-04-28 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0007_auto_20190428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 16, 1, 34, 64965, tzinfo=utc)),
        ),
    ]
