# Generated by Django 2.2 on 2019-05-10 09:52

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0008_auto_20190428_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='کد اشتراک'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 9, 52, 15, 407726, tzinfo=utc)),
        ),
    ]
