# Generated by Django 2.2 on 2019-05-10 10:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0010_auto_20190510_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MinLengthValidator(5)], verbose_name='کد اشتراک'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 10, 31, 29, 440647, tzinfo=utc)),
        ),
    ]
