# Generated by Django 2.2 on 2019-05-10 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0011_auto_20190510_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='کد اشتراک'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 10, 11, 58, 24, 843628, tzinfo=utc)),
        ),
    ]
