# Generated by Django 2.2 on 2019-06-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0012_auto_20190510_1628'),
        ('restaurant_admin', '0003_auto_20190511_1234'),
    ]

    operations = [
    ]
