# Generated by Django 2.2 on 2019-06-02 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0013_merge_20190602_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('good_response', models.IntegerField(default=0)),
                ('medium_response', models.IntegerField(default=0)),
                ('bad_response', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 14, 1, 2, 222534, tzinfo=utc)),
        ),
    ]
