# Generated by Django 2.2 on 2019-06-02 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0014_auto_20190602_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 14, 1, 12, 406213, tzinfo=utc)),
        ),
    ]
