# Generated by Django 2.2 on 2019-06-02 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0015_auto_20190602_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 2, 17, 31, 34, 545758, tzinfo=utc)),
        ),
    ]
