# Generated by Django 2.1.7 on 2019-06-03 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0017_auto_20190602_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='national_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 9, 43, 37, 805780, tzinfo=utc)),
        ),
    ]
